spring:
  application:
    name: product-service
  profiles:
    active: localhost
  main:
    allow-bean-definition-overriding: true
info:
  component: Product Service


server:
  port: 9788
logging:
  level:
    root:
    com.sonera1: DEBUG

---
spring:
  profiles: localhost
  cloud:
    config:
      uri: http://localhost:8888
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: stock_management
  datasource:
    url: "jdbc:postgresql://postgres:5432/stock_management"
    username: postgres
    password: admin
eureka:
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/

---
spring:
  profiles: stage
  cloud:
    config:
      uri: http://localhost:8888
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: stock_management
  datasource:
    url: "jdbc:postgresql://postgres:5432/stock_management"
    username: postgres
    password: admin
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
      lease-renewal-interval-in-seconds: 10
      instance-id: ${spring.application.name}:${random.uuid}







